name: Dependency Review

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'package*.json'

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
  # Skip on private repos where Dependency Review (and GHAS) is not enabled
  if: ${{ github.event.repository.private == false }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        # Fail if any vulnerabilities are found at or above this severity
        fail-on-severity: moderate
        # Enable specific checks (both are true by default, but set explicitly for clarity)
        license-check: true
        vulnerability-check: true
        # Allow only these licenses
        allow-licenses: |
          MIT
          Apache-2.0
          BSD-2-Clause
          BSD-3-Clause
          ISC
          0BSD
        # Deny these licenses
        deny-licenses: |
          GPL-2.0
          GPL-3.0
          AGPL-1.0
          AGPL-3.0
        # Comment on PR with details
        comment-summary-in-pr: always

    - name: Check dependency changes
      run: |
        echo "📦 Analyzing dependency changes..."
        
        # Check if package-lock.json was updated when package.json changed
        if git diff --name-only HEAD^ HEAD | grep -q "package.json"; then
          if ! git diff --name-only HEAD^ HEAD | grep -q "package-lock.json"; then
            echo "❌ package.json was modified but package-lock.json was not updated"
            echo "Please run 'npm install' to update package-lock.json"
            exit 1
          fi
        fi
        
        echo "✅ Dependency changes look good"

    - name: Validate new dependencies
      if: github.event_name == 'pull_request'
      run: |
        echo "🔍 Validating new dependencies..."
        
        # Get list of added dependencies
        ADDED_DEPS=$(git diff HEAD^ HEAD -- package.json | grep "^+" | grep -E '^\+\s*"[^"]+":' | sed 's/^+\s*"//;s/":.*$//' || true)
        
        if [ -n "$ADDED_DEPS" ]; then
          echo "New dependencies detected:"
          echo "$ADDED_DEPS"
          
          # Check if new deps are in common allowed list
          ALLOWED_COMMON="lodash express react vue angular typescript jest eslint prettier"
          
          for dep in $ADDED_DEPS; do
            echo "Checking dependency: $dep"
            # Additional validation could be added here
          done
        else
          echo "No new dependencies added"
        fi
        
        echo "✅ Dependency validation passed"